// C++ code to generate GetInstances class
//
// REGISTER_INSTANCE(EnumName==ctrs file name, DataFileName without extension .dat )
//
REGISTER_INSTANCE (Haverly1)
REGISTER_INSTANCE (Haverly2)
REGISTER_INSTANCE (Haverly3)

REGISTER_INSTANCE (Adhya1)
REGISTER_INSTANCE (Adhya2)
REGISTER_INSTANCE (Adhya3)
REGISTER_INSTANCE (Adhya4)

REGISTER_INSTANCE (RT2)

REGISTER_INSTANCE (Bental4)
REGISTER_INSTANCE (Bental5)

REGISTER_INSTANCE (Foulds2)
REGISTER_INSTANCE (Foulds3)
REGISTER_INSTANCE (Foulds4)
REGISTER_INSTANCE (Foulds5)

REGISTER_INSTANCE (sppA0)
REGISTER_INSTANCE (sppA1)
REGISTER_INSTANCE (sppA2)
REGISTER_INSTANCE (sppA3)
REGISTER_INSTANCE (sppA4)
REGISTER_INSTANCE (sppA5)
REGISTER_INSTANCE (sppA6)
REGISTER_INSTANCE (sppA7)
REGISTER_INSTANCE (sppA8)
REGISTER_INSTANCE (sppA9)

REGISTER_INSTANCE (sppB0)
REGISTER_INSTANCE (sppB1)
REGISTER_INSTANCE (sppB2)
REGISTER_INSTANCE (sppB3)
//REGISTER_INSTANCE (sppB4)
//REGISTER_INSTANCE (sppB5)

REGISTER_INSTANCE (sppC0)
REGISTER_INSTANCE (sppC1)
REGISTER_INSTANCE (sppC2)
REGISTER_INSTANCE (sppC3)

